name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: |
          echo "Checking Fly.io app existence"
          flyctl apps list
          echo "Deploying to app millzmaleficarum-portal-v05"
          flyctl deploy --remote-only --app millzmaleficarum-portal-v05 --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}