name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Verify Fly.io authentication and apps
        run: |
          echo "Checking Fly.io authentication status"
          flyctl auth whoami
          echo "Listing available Fly.io apps"
          flyctl apps list
          
      - name: Deploy to Fly.io
        run: |
          echo "Deploying to app millzmaleficarum-portal-v05"
          flyctl deploy --remote-only --app millzmaleficarum-portal-v05 --config fly.toml
          echo "Deployment completed"